version: '3.1'
services:
  rabbitmq:
    restart: always
    image: registry.cn-beijing.aliyuncs.com/mufeng_blog/rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: mufeng2023
    volumes:
      - ../data/rabbitmq_data:/var/lib/rabbitmq/mnesia
    networks:
      - mogu
      
networks:
  mogu:
    external: true
